### PR TITLE
Disconnect clients when monolith connection is severed

### LINKED ISSUE #1076: Balancer should disconnect clients when the upstream connection to the monolith is severed.
### Current Behavior

The balancer does not do this, and it results in join messages not being resent, and this log message is emitted

```
2023-09-23T16:03:05.045 app[591854ead93383] ewr [info] 2023-09-23 16:03:05 clientmanager error Balancer sent message for client that does not exist or is not a balancer client 
```

### Expected Behavior

The balancer should disconnect all clients when the upstream monolith connection is interrupted to allow them to reconnect. 

Alternatively, it would be possible to avoid the reconnect overhead if the balancer could send joins when the connection is reestablished. But that sounds like a premature optimization.

### Steps To Reproduce

1. Start a monolith
2. Start a balancer
3. Create a room and join it
4. Restart the monolith
5. Send a message in chat
6. See error log message in monolith logs
7. See that chat message does not appear in chat.

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

The workaround is to have the clients refresh the page.

### PR DESCRIPTION
**Pull request by cjrkoa**
fixes #1076

### CODE REVIEW

**Comment by dyc3** [comment]
You gotta work on your PR titles.

**Comment by cjrkoa** [comment]
fixes #1076

File: crates/ott-balancer-bin/src/balancer.rs [hunk 1]
```diff
@@ -262,8 +262,23 @@ impl BalancerContext {
...
+            .retain(|_, v| *v != monolith_id);
+
+        self.clients
+            .retain(|_, v| self.rooms_to_monoliths.contains_key(&v.room));
+        
+        for client in self.clients.values(){ 
+            client.send(SocketMessage::Message(Message::Close(Some(CloseFrame {
+                code: CloseCode::Library(1006),
+                reason: "Monolith disconnect".into(),
+            })))).await?;
```
Comment (dyc3) [inline crates/ott-balancer-bin/src/balancer.rs:278]: if this fails, it would prevent the disconnects of any subsequent clients. we can't let errors break this for loop.

File: crates/ott-balancer-bin/src/balancer.rs [hunk 2]
```diff
@@ -262,8 +262,23 @@ impl BalancerContext {
...
+        
+        self.rooms_to_monoliths
+            .retain(|_, v| *v != monolith_id);
+
+        self.clients
+            .retain(|_, v| self.rooms_to_monoliths.contains_key(&v.room));
+        
+        for client in self.clients.values(){ 
+            client.send(SocketMessage::Message(Message::Close(Some(CloseFrame {
+                code: CloseCode::Library(1006),
```
Comment (dyc3) [inline crates/ott-balancer-bin/src/balancer.rs:276]:
```suggestion
                code: CloseCode::Away,
```

**Review by dyc3 — APPROVED** [review]
