### PR TITLE
balancer: fix infinite loop in client connection handling

### LINKED ISSUE #1187: Balancer stops responding to all HTTP requests when Monolith stops
### Current Behavior

When a monolith restarts, the balancer becomes completely unresponsive.

### Expected Behavior

1. Balancer should disconnect all clients connected to the monolith
2. Balancer should continue responding to HTTP requests, including `GET /api/status`

### Steps To Reproduce

1. Set up 2 monolith, 1 balancer
2. Create a room
3. Stop the monolith that has the room
```
fly machines stop --app ott-staging --select
```
4. See that Balancer becomes unresponsive, no longer responds to `GET /api/status`

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Found when manually testing on the staging deployment.

This is most likely the result of a deadlock.

### PR DESCRIPTION
**Pull request by dyc3**
fixes #1187

### CODE REVIEW

File: crates/ott-balancer/src/client.rs [hunk 1]
```diff
@@ -183,36 +183,38 @@ pub async fn client_entry<'r>(
...
                 } else {
-                    continue;
+                    info!("Client outbound stream ended");
+                    break;
                 }
             }
 
-            msg = stream.next() => {
-                if let Some(Ok(msg)) = msg {
+            Some(msg) = stream.next() => {
```
Comment (Victor-M-Giraldo) [inline crates/ott-balancer/src/client.rs:198]: Is this using pattern matching?

**Review by Victor-M-Giraldo — APPROVED** [review]

File: crates/ott-balancer/src/client.rs (hunk 1 above)
Comment (dyc3) [reply crates/ott-balancer/src/client.rs:198]: Yes, see the docs for `tokio::select!`
