### PR TITLE
Client: Extract HLS logic to a new HlsPlayer Component

### LINKED ISSUE #1872: Client: Chrome doesn't show subtitles in HLS Stream
### Current Behavior

The CC/Subtitles Feature does not work on chrome as stated in #1866.

### Expected Behavior

Subtitles should be displayed as in Firefox

### Steps To Reproduce

Open Chrome
Visit offical OTT Site
Open a room
Pick a HLS Stream with CC/Subtitles copy the link and paste it into the add form and press play
Enable subtitles
See no captions

### Environment

- [x] This happens on the official site, opentogethertube.com
- [x] This happens using a self-hosted version.
- [x] I'm using the docker image.

### Room name or URL

_No response_

### Video URL

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by WuTofu**
This PR introduced a new HlsPlayer.vue component, extracting hls.js logic from PlyrPlayer.vue.

1. Added HlsPlayer.vue for HLS playback and captions support (Fix #1872).
2. Updated OmniPlayer.vue to use HlsPlayer for hls sources.
3. Removed hls.js integration from PlyrPlayer.vue; Plyr now only handles direct and DASH sources.
4. Updated package.json and yarn.lock to use hls.js v1.6.12. 
  (I was having a bug where captions failed to load after switching to a new hls stream, but this issue was resolved by bumping the hls.js version.)
5. Minor improvements to captions switching UI.

### CODE REVIEW

File: client/src/components/players/HlsPlayer.vue [hunk 1]
```diff
@@ -0,0 +1,250 @@
...
+			if (!videoElem.value) {
+				console.error("video element not ready");
+				return;
+			}
+
+			hls?.destroy();
+			hls = undefined;
+
+			videoElem.value.setAttribute("crossorigin", "anonymous"); // For WebVTT captions
+			videoElem.value.setAttribute("poster", thumbnail.value || "");
```
Comment (dyc3) [inline client/src/components/players/HlsPlayer.vue]: This is kind of an anti pattern in vue. You should do this in the template.

File: client/src/components/players/HlsPlayer.vue [hunk 2]
```diff
@@ -0,0 +1,250 @@
+<template>
+	<div class="hls">
+		<video id="hlsplayer" preload="auto"></video>
+	</div>
+</template>
+
+<script lang="ts">
```
Comment (dyc3) [inline client/src/components/players/HlsPlayer.vue]: Prefer using `<script setup>` style components

```suggestion
<script lang="ts" setup>
```

File: client/src/components/players/HlsPlayer.vue [hunk 3]
```diff
@@ -0,0 +1,250 @@
...
+			},
+
+			isCaptionsSupported(): boolean {
+				return true;
+			},
+			setCaptionsEnabled(enabled: boolean): void {
+				if (!hls) {
+					return;
+				}
+				if (enabled === false) {
```
Comment (dyc3) [inline client/src/components/players/HlsPlayer.vue]: nit
```suggestion
				if (!enabled) {
```

File: client/src/components/players/OmniPlayer.vue [hunk 4]
```diff
@@ -59,10 +59,25 @@
...
+				@buffering="onBuffering"
+				@error="onError"
+				@buffer-progress="onBufferProgress"
+				@buffer-spans="onBufferSpans"
+			/>
 			<PlyrPlayer
 				v-else-if="
 					!!source &&
-					['direct', 'hls', 'dash', 'reddit', 'tubi', 'pluto'].includes(source.service)
+					['direct', 'dash', 'reddit', 'tubi', 'pluto'].includes(source.service)
```
Comment (dyc3) [inline client/src/components/players/OmniPlayer.vue]: `pluto` also needs to be moved. it uses HLS. `tubi` also uses HLS, but the info extractor is broken right now.

Comment (Sysadminfromhell) [reply client/src/components/players/OmniPlayer.vue]: @dyc3 tubi is broken? since when? You opened an issue for that?

Comment (dyc3) [reply client/src/components/players/OmniPlayer.vue]: Have no idea when, nobody was complaining about it. #1882

Comment (Sysadminfromhell) [reply client/src/components/players/OmniPlayer.vue]: @dyc3 cant have a look on that. TubiTV is not available in my country. Therefore someone else needs to have a look at that. Sorry

**Comment by WuTofu** [comment]
Thanks for the review! I've just pushed the changes based on your feedback.

**Review by dyc3 — APPROVED** [review]
