### PR TITLE
harness: add `TestRunner::restart_balancer()`

### LINKED ISSUE #1140: add function to restart balancer to harness
For some tests, we need to be able to restart the balancer so that we can assert how it recovers from crashes or on fresh start

### PR DESCRIPTION
**Pull request by dyc3**
closes #1140

### CODE REVIEW

File: crates/harness/src/test_runner.rs [hunk 1]
```diff
@@ -8,8 +8,7 @@ use tracing::warn;
 use crate::util::random_unused_port;
 
 pub struct TestRunner {
-    /// The port that the balancer is listening on for client connections.
-    pub port: u16,
+    spawn_options: BalancerSpawnOptions,
```
Comment (cjrkoa) [inline crates/harness/src/test_runner.rs:11]: what does this do?

File: crates/harness/src/test_runner.rs [hunk 2]
```diff
@@ -44,10 +43,10 @@ impl AsyncTestContext for TestRunner {
                 "--log-level",
                 "debug",
             ])
-            .env("BALANCER_PORT", format!("{}", port))
+            .env("BALANCER_PORT", format!("{}", opts.port))
```
Comment (cjrkoa) [inline crates/harness/src/test_runner.rs:46]: opts.port vs port?

**Review by cjrkoa — APPROVED** [review]

File: crates/harness/src/test_runner.rs (hunk 1 above)
Comment (dyc3) [reply crates/harness/src/test_runner.rs:11]: BalancerSpawnOptions is used to hold the parameters used to start the balancer. They are held here to so they can be reused when restarting the balancer.
