### PR TITLE
Server: Ffprobe leak fix

### LINKED ISSUE #1056: ffprobe process leak
### Current Behavior

Sometimes, ffprobe processes remain open when they are no longer having data piped into them.

This only seems to occur with `ffprobe_strategy = "stream"`.

### Expected Behavior

If the request for a direct video times out, ffprobe should be terminated.

### Steps To Reproduce

Precise steps unknown, but probably

1. Open a room
2. Attempt to preview a direct video that takes > 30 seconds to process
3. See request time out
4. See ffprobe still running

### Environment

- [X] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Sysadminfromhell**
Should close #1056.

This PR Does the following:
- sets a hard timeout of 35 sec to the ffprobe and displays a error to the user via UI/UX.
- spawns all ffprobe as childs
- keep track of all ffprobes and kills them properly (multi-spawn bug)
- Kills all known ffprobe spawns when a process interrupt kill is registered.

Test file: https://ftp.nluug.nl/pub/graphics/blender/demo/movies/ToS/tearsofsteel_4k.mov

### CODE REVIEW

**Comment by Sysadminfromhell** [comment]
@dyc3 how is the ET of your review to this?

**Comment by dyc3** [comment]
I'll take a look at it soon. Been very busy with work.

File: server/exceptions.ts [hunk 1]
```diff
@@ -71,6 +71,21 @@ export class InvalidAddPreviewInputException extends OttException {
...
 
+export class FfprobeTimeoutError extends OttException {
+	public readonly status: number = 408;
+	public readonly code: "UPSTREAM_FFPROBE_TIMEOUT" = "UPSTREAM_FFPROBE_TIMEOUT";
+	public readonly userMessage: string;
+	public readonly expose: boolean = true;
+
+	constructor() {
+		const userMessage =
+			"The provided direct file needs too long to probe. Please try another file.";
```
Comment (dyc3) [inline server/exceptions.ts]:
```suggestion
			"The provided direct file took too long to probe for metadata. Please try another file.";
```

**Review by dyc3 — APPROVED** [review]
